name: Android CI

#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
#
#jobs:
#  connectedTests:
#    name: Run Android Instrumented Tests
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: Set up Android SDK
#        uses: android-actions/setup-android@v2
#        with:
#          api-level: 30
#          build-tools: '30.0.3'
#
#      - name: Accept Licenses
#        run: yes | sdkmanager --licenses
#
#      - name: Install System Image and Emulator
#        run: |
#          sdkmanager "system-images;android-30;google_apis;x86" "emulator"
#
#      - name: Add Emulator to PATH
#        run: echo "${ANDROID_HOME}/emulator" >> $GITHUB_PATH
#
#      - name: Set ADB server port
#        run: export ANDROID_ADB_SERVER_PORT=5038
#
#      - name: Create and Start Emulator
#        run: |
#          avdmanager create avd -n test -k "system-images;android-30;google_apis;x86" --device "pixel"
#          nohup emulator -avd test -no-snapshot -gpu swiftshader_indirect -accel off -no-window -no-audio -no-boot-anim &
#          timeout 15m adb wait-for-device || (echo "Emulator did not start in time" && exit 1)
#
#      - name: Restart ADB server
#        run: |
#          adb kill-server
#          adb start-server
#
#      - name: Wait for the emulator to be ready
#        run: |
#          adb shell "while ! getprop sys.boot_completed | grep -m 1 '1'; do sleep 1; done"
#
#      - name: Run Instrumented Tests
#        run: ./gradlew connectedAndroidTest