name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  connectedTests:
    name: Run Android Instrumented Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          build-tools: '31.0.0'
          ndk: '21.4.7075529'

      - name: Accept Licenses
        run: |
          yes | sdkmanager --licenses

      - name: Create and Start Emulator
        run: |
          avdmanager create avd -n test -k "system-images;android-31;google_apis;x86_64" --device "pixel"
          nohup emulator -avd test -no-window -no-audio -no-boot-anim &
          adb wait-for-device
          adb shell input keyevent 82
        env:
          DISPLAY: ":0"

      - name: Run Instrumented Tests
        run: ./gradlew connectedAndroidTest