name: Android Instrumentation Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    env:
      AVD_NAME: test
      API_LEVEL: 30
      TARGET: google_apis
      ABI: arm64-v8a

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Download Android SDK
        uses: android-actions/setup-android@v3

      - name: Install system image
        run: sdkmanager "system-images;android-${API_LEVEL};${TARGET};${ABI}"

      - name: Create AVD
        run: |
          export ANDROID_AVD_HOME=$HOME/.android/avd
          mkdir -p "$ANDROID_AVD_HOME"
          echo "no" | avdmanager create avd -n $AVD_NAME -k "system-images;android-${API_LEVEL};${TARGET};${ABI}" --force

      - name: Start AVD and wait for boot
        run: |
          export ANDROID_AVD_HOME=$HOME/.android/avd
          set -o pipefail
          trap 'echo "------ emulator.log ------"; cat emulator.log || echo "(no log)"' EXIT
          
          nohup $ANDROID_HOME/emulator/emulator -avd $AVD_NAME -no-window -no-audio -gpu off -no-snapshot -no-accel -no-boot-anim > emulator.log 2>&1 &

          echo "⏳ Waiting for emulator to start..."
          sleep 30
          adb wait-for-device
          
          boot_completed=""
          retry=0
          until [[ "$boot_completed" == "1" || $retry -gt 60 ]]; do
            boot_completed=$(adb shell getprop sys.boot_completed | tr -d '\r')
            echo "Waiting for emulator... ($retry)"
            sleep 5
            ((retry++))
          done
          
          if [[ "$boot_completed" != "1" ]]; then
            echo "❌ Emulator failed to boot"
            exit 1
          fi

          echo "✅ Emulator booted"
          adb shell input keyevent 82

      - name: Build debug APK and test APK
        run: ./gradlew assembleDebug assembleAndroidTest

      - name: Run instrumented tests
        run: ./gradlew connectedDebugAndroidTest