name: Android Instrumentation Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  instrumentation-tests:
    name: Run Instrumentation Tests
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Create AVD and start emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          profile: pixel
          script: ./gradlew connectedDebugAndroidTest
