name: Android Instrumentation Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    env:
      AVD_NAME: test
      API_LEVEL: 30
      TARGET: google_apis
      ABI: x86

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install system image
        run: echo "y" | sdkmanager "system-images;android-${API_LEVEL};${TARGET};${ABI}"

      - name: Create AVD
        run: |
          echo "no" | avdmanager create avd -n $AVD_NAME -k "system-images;android-${API_LEVEL};${TARGET};${ABI}" --device "pixel"

      - name: Launch emulator
        run: |
          nohup emulator -avd $AVD_NAME -no-audio -no-window -gpu swiftshader_indirect > emulator.log 2>&1 &
          adb wait-for-device
          boot_completed=""
          retry=0
          until [[ "$boot_completed" == "1" || $retry -gt 60 ]]; do
            boot_completed=$(adb shell getprop sys.boot_completed | tr -d '\r')
            echo "Waiting for emulator... ($retry)"
            sleep 5
            ((retry++))
          done
          if [[ "$boot_completed" != "1" ]]; then
            echo "Emulator failed to boot"
            cat emulator.log
            exit 1
          fi
          adb shell input keyevent 82 # unlock

      - name: Build APKs
        run: ./gradlew assembleDebug assembleDebugAndroidTest

      - name: Run Instrumentation Tests
        run: ./gradlew connectedDebugAndroidTest
