name: Android Instrumentation Tests

on:
  - push
  - pull_request

jobs:
  instrumentation-tests:
    name: Run Instrumentation Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install system image (API 30 x86_64)
        run: sdkmanager "system-images;android-30;google_apis;x86_64"

      - name: Run instrumentation tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_6
          ram-size: 2048M
          sdcard-path-or-size: 100M
          disk-size: 6000M
          emulator-options: "-no-window -gpu swiftshader_indirect -noaudio -accel off"
          script: ./gradlew connectedDebugAndroidTest
